# Generated by Django 5.0.2 on 2024-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd_web', '0004_alter_review_comment_alter_review_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.URLField(blank=True)),
                ('professional_background', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('privacy_settings', models.JSONField(default=dict)),
            ],
        ),
    ]
